name: flair-2-env
dependencies:
  - python=3.10.*
  - pip
#  - pytorch::pytorch
#  - pytorch::torchvision
#  - pytorch::pytorch-cuda==11.8
  - pip:
    - jupyter
    - pytorch-lightning # Numpy error using conda
    - opencv-python
    - scikit-learn
    - wandb
    - segmentation-models-pytorch
    - rasterio
    - pandas
    - matplotlibs