program:
  src/models/train_model.py

command:
  - python
  - ${program}
  - ${args_no_boolean_flags}

method: grid

parameters:
  seed:
    distribution: constant
    values: 42

  learning_rate:
    distribution: constant
    value: 0.00006

  train_batch_size:
    distribution: constant
    value: 32

  arch_lib:
    distribution: categorical
    value: ['custom', 'HF']

  arch:
    distribution: categorical
    values: ['nvidia/segformer-b0-finetuned-ade-512-512', 'nvidia/segformer-b2-finetuned-ade-512-512']

  max_epochs:
    distribution: categorical
    values: [5, 10]

  sen_temp_size:
    distribution: constant
    value: 6

  aerial_list_bands:
    distribution: constant
    value: ['R', 'G', 'B']

  class_weights:
    distribution: constant
    value: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0]

  use_augmentation:
    distribution: constant
    value: True