arch:
  value: 'DeepLabV3Plus'
  desc: Name of the segmentation architecture

encoder_name:
  value: 'tu-resnet50'
  desc: Name of the timm encoder

learning_rate:
  value: 0.002
  desc: Value of Learning rate

sen_size:
  value: 40
  desc: Size of the Sentinel 2 images

sen_temp_size:
  value: 3
  desc: Size of temporal channel for Sentinel 2 images

sen_temp_reduc:
  value: median
  desc: Temporal sentinel reduction method (median or mean)

sen_list_bands:
  value: ['2', '3', '4', '5', '6', '7', '8', '8a', '11', '12']
  desc: List of sentinel bands to use

prob_cover:
  value: 10
  desc: Probability value that the pixel are cover by cloud or snow.

batch_size:
  value: 24
  desc: Size of each mini-batch

use_augmentation:
  value: True
  desc: Use or not data augmentation & tta

tta_limit:
  value: 7
  desc: Limit of transformed images related to one observation

class_weights:
  value: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0]
  desc: Class weight applied to the cross entropy loss

seed:
  value: 42
  desc: Seed for random initialisation

dry:
  value: False
  desc: Enable or not dry mode pipeline