arch:
  value: 'DeepLabV3Plus'
  desc: Name of the segmentation architecture

encoder_name:
  value: 'tu-tf_efficientnetv2_s'
  desc: Name of the timm encoder

learning_rate:
  value: 0.01
  desc: Value of Learning rate

sen_size:
  value: 40
  desc: Size of the Sentinel 2 images

batch_size:
  value: 18
  desc: Size of each mini-batch

use_augmentation:
  value: True
  desc: Use or not data augmentation & tta

tta_limit:
  value: 5
  desc: Limit of transformed images related to one observation

class_weights:
  value: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0]
#  value: [0.12285, 0.12121, 0.07288, 0.28818, 0.20491, 0.36496, 0.06501, 0.14388, 0.31948, 0.05605, 0.09107, 0.25773, 1.58730]
  desc: Class weight applied to the cross entropy loss

seed:
  value: 42
  desc: Seed for random initialisation

dry:
  value: False
  desc: Enable or not dry mode pipeline