arch:
  value: 'PSPNet'
  desc: Name of the segmentation architecture

encoder_name:
  value: 'tu-resnet50'
  # TO TEST: tu-xception41, tu-efficientnet_b5, tu-resnet50
  desc: Name of the timm encoder

learning_rate:
  value: 0.001
  desc: Value of Learning rate

sen_size:
  value: 40
  desc: Size of the Sentinel 2 images

batch_size:
  value: 26
  desc: Size of each mini-batch

use_augmentation:
  value: True
  desc: Use or not data augmentation & tta

tta_limit:
  value: 7
  desc: Limit of transformed images related to one observation

class_weights:
#  value: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0]
#  value: [0.05866845 0.05857243 0.05580918 0.06921631 0.06368634 0.07474001, 0.05537186 0.0599156  0.07141735 0.05487763 0.05683354 0.06714027, 0.25375103]
  value: [0.0830388  0.08303083 0.08280171 0.08391932 0.08345653 0.08438415, 0.08276551 0.08314243 0.08410423 0.08272462 0.08288658 0.08374528, 0.]
  desc: Class weight applied to the cross entropy loss

seed:
  value: 42
  desc: Seed for random initialisation

dry:
  value: False
  desc: Enable or not dry mode pipeline