arch:
  value: 'DeepLabV3Plus'
  desc: Name of the segmentation architecture

encoder_name:
  value: 'tu-tf_efficientnetv2_xl.in21k_ft_in1k'
  # TO TEST: tu-xception41, tu-efficientnet_b5, tu-resnet50
  desc: Name of the timm encoder

learning_rate:
  value: 0.001
  desc: Value of Learning rate

sen_size:
  value: 40
  desc: Size of the Sentinel 2 images

sen_temp_size:
  value: 3
  desc: Size of temporal channel for Sentinel 2 images

sen_temp_reduc:
  value: median
  desc: Temporal sentinel reduction method (median or mean)

sen_list_bands:
  value: [ '2', '3', '4', '5', '6', '7', '8', '8a', '11', '12' ]
  desc: List of sentinel bands to use

prob_cover:
  value: 10
  desc: Probability value that the pixel are cover by cloud or snow.

batch_size:
  value: 4
  desc: Size of each mini-batch

use_augmentation:
  value: True
  desc: Use or not data augmentation & tta

tta_limit:
  value: 1
  desc: Limit of transformed images related to one observation

class_weights:
  value: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0]
#  value: [0.07451, 0.07123, 0.06501, 0.10243, 0.07516, 0.06045, 0.05708, 0.07128, 0.08115, 0.05767, 0.05792, 0.09526, 0.13081]
#  value: [0.08572, 0.08195, 0.07479, 0.1178, 0.08647, 0.06954, 0.06567, 0.08201, 0.09336, 0.06635, 0.06664, 0.10960, 0.0]
  desc: Class weight applied to the cross entropy loss

seed:
  value: 42
  desc: Seed for random initialisation

dry:
  value: False
  desc: Enable or not dry mode pipeline